### ISSUE TITLE
Chef::Exceptions::RecipeNotFound:

### ISSUE THREAD

**Issue by bheuvel** [chefspec/chefspec#782] opened 2016-11-24 19:46 UTC
This problem DOES appear for me in Chef-DK 0.19.6 and 1.1.3  (rspec 3.5.4)
This problem does NOT appear for me in Chef-DK 0.17.17 (rspec 3.5.2)

__Problem__
When using the following line with chefspec:
```
...
before do
  allow(File).to receive(:file?).and_return(false)
...
```
it results in `Chef::Exceptions::RecipeNotFound:`:
```
Failures:

  1) mycookbook::agent when all attributes are default converges successfully
     Failure/Error: expect { chef_run }.to_not raise_error

       expected no Exception, got #<Chef::Exceptions::RecipeNotFound: could not find recipe agent for cookbook mycookbook> with backtrace:
         # ./spec/chef/recipes/agent_spec.rb:121:in `block (3 levels) in <top (required)>'
         # ./spec/chef/recipes/agent_spec.rb:137:in `block (4 levels) in <top (required)>'
         # ./spec/chef/recipes/agent_spec.rb:137:in `block (3 levels) in <top (required)>'
     # ./spec/chef/recipes/agent_spec.rb:137:in `block (3 levels) in <top (required)>'
```

When using
```
...
before do
  allow(File).to receive(:file?).with('/whatever').and_return(true)
...
```
it reveals the non-matching paths it receives:
```
       #<File (class)> received :file? with unexpected arguments
         expected: ("/whatever")
              got: ("/tmp/d20161124-971-7ebuyj/cookbooks/mycookbook_test/recipes")
        Please stub a default value first if message might be received with other args as well. 
```

The location `/tmp/d20161124-971-7ebuyj/cookbooks/mycookbook_test/recipes` seems to me more something which is done to get to starting the chefrun, while I would expect the `allow(File)` to mock __only during__ the chef run.

__Workaround__
When using
```
...
before do
      allow(File).to receive(:file?).and_return(false)
      allow(File).to receive(:file?).with(/\/tmp\//).and_return(true)
...
```
It works again, as with the older ChefDK version. Though it doesn't feel right as it forces the `file?` check to `true` for setting up the chef run

Apologies if I'm overlooking something, or posting to the wrong repo. 

__Some details:___
mycookbook::agent : our private cookbook/recipe
cookbook mycookbook simplified folder tree:
```
.
├── attributes
├── files
├── recipes
├── spec
├── templates
└── test_cookbooks
       └── mycookbook_test
```

**Comment by lamont-granquist** [comment] 2017-04-18 14:44
You're stubbing every `File.file?` call and forcing it to return false.  There's no restriction to your own code so it stubs that call inside of the cookbook loader somewhere and returns false when chef itself is trying to load cookbooks.  The cookbook loader code probably changed to call 1File.file?` for some reason in between those versions, but that is not a bug or a breaking change.

Something like this pattern has to be used:

```ruby
before do
  # avoid breaking all of chef
  allow(File).to receive(:file?).and_call_original
end

it "whatever" do
  # stub only the call we need to stub
  expect(File).to receive(:file?).with("/the-path-i-actually-want-to-text").and_return(false)
end
```

@tas50 this is another rspec question and not a bug report.

**Comment by davidalpert** [comment] 2017-10-02 00:52
@tas50 @lamont-granquist 

Recommend closing this issue; @lamont-granquist's comment above just addressed and resolved my experience with the same behaviour.

**Closed** 2018-05-08 18:07 UTC
